export const uiIcons = {
	actions: {
		add: "material-symbols:add-rounded",
		cancel: "iconoir:cancel",
		check: "lucide:check",
		magnify: "mdi:magnify",
		delete: "mingcute:delete-2-line",
		upload: "solar:upload-linear",
	},
	auth: {
		google: "flat-color-icons:google",
		facebook: "logos:facebook",
	},
	profile: {
		account: "mdi-light:account",
		bell: "mdi-light:bell",
		upload: "mdi-light:upload",
		settings: "mdi-light:settings",
		logout: "mdi-light:logout",
	},
	content: {
		heartFilled: "mdi:heart",
		heartOutline: "mdi-light:heart",
		calendar: "mdi-light:calendar",
		clock: "mdi:clock-outline",
		bookOutline: "mdi:book-open-variant-outline",
		bookFilled: "mdi:book-open",
		folder: "mdi:folder",
		comment: "iconamoon:comment-light",
		chefHat: "hugeicons:chef-hat",
		usersGroup: "flowbite:users-group-outline",
	},
	star: {
		filled: "material-symbols-light:star-rounded",
		outline: "material-symbols-light:star-outline-rounded",
	},
	nav: {
		hamburger: "charm:menu-hamburger",
		globe: "material-symbols:globe",
		chevronDown: "tabler:chevron-down",
		chevronRight: "tabler:chevron-right",
		chevronLeft: "tabler:chevron-left",
		filter: "majesticons:filter-line",
	},
	visibility: {
		eyeOpen: "lucide:eye",
		eyeClosed: "lucide:eye-off",
	},
	badges: {
		topContributor: "fluent:star-add-24-filled",
		recipeVeteran: "mdi:crown",
		earlyAdopter: "mdi:rocket-launch",
		firstRecipe: "material-symbols:flag",
		uploadStreak: "mdi:calendar-range",
		topRated: "mdi:star-check",
		mostFavorited: "mdi:heart-multiple",
		commentHero: "mdi:comment-multiple-outline",
		communityHelper: "mdi:account-heart",
		trending: "mdi:trending-up",
		viral: "mdi:fire",
		fusionMaster: "mdi:chef-hat",
		photogenic: "mdi:camera",
		onePot: "mdi:pot-steam-outline",
		mealPrep: "mdi:clock-outline",
		holidayHero: "mdi:pine-tree",
		dessertWizard: "mdi:cake-variant",
		plantBased: "mdi:leaf",
	},
} as const;

export type UiIconKeys = keyof typeof uiIcons;
